version: '3.8'
services: 
  db: 
    container_name: docker-postgres
    # hostname: postgres
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis: 
    container_name: redis-stack-server
    image: redis/redis-stack-server:latest
    ports: 
      - ${REDIS_PORT}:6379
    restart: always
    command: redis-stack-server --save 20 1
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
    volumes:
      - ./docker/redis:/data
    depends_on:
    - db
    environment:
      - REDIS_HOST=redis-stack-server

  migrate:
    image: server
    command: npx prisma migrate dev --name init
    depends_on: 
      db: 
        condition: service_healthy

  api:
    container_name: express-api 
    image: server
    ports: 
    # LOCAL PORT:DOCKER CONTAINER PORT
      - ${NODE_PORT}:8080
    restart: always
    depends_on:
      db: 
        condition: service_healthy
      redis: 
        condition: service_healthy
      migrate: 
        condition: service_started
    healthcheck:
      test: ["CMD", "node", "utils/healthcheck-express.js"]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 5s
    
  client:
    # containter_name: next_client
    image: client
    ports: 
      - ${CLIENT_PORT}:3000
    restart: always
    depends_on: 
      api: 
        condition: service_healthy