import { Metadata } from 'next';
import Navigation from './components/Navigation';
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <section>
            <Navigation />
            {children}
        </section>
    );
}
